version: "2"
services:

 my-mongodb:
  image: mongo
  ports:
   - "27017:27017"
  networks:
   - nodeapp-network

 mongo-seed:
  build: ./mongo-seed/
  networks:
    - nodeapp-network
  depends_on:
    - my-mongodb

 taxis:
  build:
   context: ./taxis/
  ports:
    - "8080:8080"
  networks:
    - nodeapp-network
  command: >
       bash -c "npm start"

 server:
  build:
   context: ./server/
  ports:
    - "5000:5000"
  #volumes:
  # - ./server/:/usr/app/
  networks:
    - nodeapp-network
  depends_on:
    - mongo-seed
  command: >
       bash -c "npm start"

networks:
 nodeapp-network:
  driver: bridge