sh.enableSharding("taxisService");
printjson("taxisService sharding enabled");
db.createCollection("taxisService.clients");
printjson("clients collection is crieted");
sh.shardCollection("taxisService.clients", { ClientsShardingField: 1 });
printjson("clients collection is sharded");
db.createCollection("taxisService.orders");
printjson("orders collection is crieted");
sh.shardCollection("taxisService.orders", { ordersShardingField: 1 });
printjson("orders collection is sharded");
db.createCollection("taxisService.tracks");
printjson("tracks collection is crieted");
sh.shardCollection("taxisService.tracks", { tracksShardingField: 1 });
printjson("tracks collection is sharded");